version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - $HOME/postgresql_16/data:/var/lib/postgresql/data
      - pg_data:/var/lib/postgresql/data
      - ./src/db/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
volumes:
  pg_data: